### ISSUE TITLE
Allow the map to dynamically load GIS Layers from GeoNode

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/disastermanagement-client#30]
An Admin must be able to select more background Layers from GeoNode and associate them to a Risk Analsyis.

Those Layers must be loaded into the map configuration at Risk Analysis level (not checked by default) and selectable via a Layer Switcher

![image](https://cloud.githubusercontent.com/assets/1278021/23893446/c11ef7de-089e-11e7-9889-a889e25f21e3.png)

**Comment by cezio** [comment]
for the record:

 * layers can be fetched from ``/api/layers`` endpoint
 * layers selection should be saved to geonode, can be global.

**Comment by cezio** [comment]
Correct my understanding of workflow here:
 * map loads base layer, geometry based on data view
 * map loads available layers from api (``/api/layers``), shows them in layers control
 * user selects/deselects additional layers
 * when selected layers set changes, map saves selection to risk analysis through ``/risks/risk/<id>/layers/`` (or something similar). This will save selected layers per-risk analysis.
 * saved layers are returned for map view as a part of ``riskAnalysisData``, for example ``additionalLayers``. 

 questions:
 * should map view show layers that are within bbox for analysis area, or all available?
 * should server return selected layers just as a list of names or with more metadata, in similar way as in #23?

**Comment by afabiani** [comment]
About #1, all available.

About #2
Well it depends on client configuration, however list of typenames should be sufficient, since they are all internal resources of GeoNode.

Must be clear that those are additional layers and can be selected only via map layer switcher control, while the layer on https://github.com/geosolutions-it/disastermanagement-client/issues/23 is always visible by default.

**Comment by cezio** [comment]
this should be fixed in geonode repo now: https://github.com/geosolutions-it/geonode/issues/30

**Comment by cezio** [comment]
Usage info:
 * risk view will have ``riskAnalysisData.additionalLayers`` list with layers selected in previous views. This list will contain id and title of layer
 * map client should load all layers  from ``/api/layers``
 * if selected layers set changes, map should do following request:
```
POST /risks/api/risk/<risk id>/layers/

layers=layer1_id,layer2_id
```
 each update should contain full set of selected layers (id values).
