### ISSUE TITLE
Loading Risk Analysis data from admin dashboard

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/disastermanagement-client#33]
Loading Risk Analysis data from admin dashboard is a process that may require long time. This is currently a call to a management command that loads data from an excel file.

We should envisage ways to:

1. Provide some sort of feedback to the user (at least that the process is running and it's not blocked)

2. Avoid HTTP session timeouts

We can also envisage to move the management command logic into an helper class and recall the functions from DJango instead of relying on a simple "call_command" call.

**Comment by cezio** [comment]
we could handle upload in admin, then record import process somehow (status in risk analysis record), then run background task (subprocess with detached terminal, celery task maybe) which will update record after job is done. in ui we can check status from time to time with js.

**Comment by cezio** [comment]
fixed in https://github.com/geosolutions-it/geonode/issues/42
